### ISSUE TITLE
My goodness, what's the state of this?

### ISSUE THREAD

**Issue by ghost** [abergmeier/mesa-vulkan-broadcom#1]
Another request, did you think on merge this on mesa somewhere in time?

**Comment by Hugobros3** [comment]
Having attended the talk @abergmeier gave about this at FOSDEM yesterday, he works on this on his spare time and at that rate this is going to be a while! The rpi foundation has just announced an [official driver](https://www.raspberrypi.org/blog/vulkan-raspberry-pi-first-triangle/) being worked on by Igalia, you can bet one driver or another will eventually ship by 2021, but nothing right now.

**Comment by ghost** [comment]
Thanks!
